config/routes.rb
Weightloss::Application.routes.draw do

  resources :chats

  get "sessions/new"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users do
    resources :weight_logs
  end
  
  resources :sessions

  root :to => 'home#index'

end

app/models/weight_log.rb
class WeightLog
  include Mongoid::Document
  include Mongoid::Timestamps

  field :weight, type: Float

  belongs_to :user
  
end

app/controllers/weight_logs_controller.rb
class WeightLogsController < ApplicationController
  # GET /weight_logs
  # GET /weight_logs.json
  def index
    @weight_logs = current_user.weight_logs.asc(:created_at)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @weight_logs }
    end
  end

  # GET /weight_logs/1
  # GET /weight_logs/1.json
  def show
    @weight_log = current_user.weight_logs.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @weight_log }
    end
  end

  # GET /weight_logs/new
  # GET /weight_logs/new.json
  def new
    @weight_log = WeightLog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @weight_log }
    end
  end

  # GET /weight_logs/1/edit
  def edit
    @weight_log = current_user.weight_logs.find(params[:id])
  end

  # POST /weight_logs
  # POST /weight_logs.json
  def create
    @weight_log = current_user.weight_logs.new(params[:weight_log])

    respond_to do |format|
      if @weight_log.save
        format.html { redirect_to root_url, notice: 'Weight log was successfully created.' }
        format.json { render json: @weight_log, status: :created, location: @weight_log }
      else
        format.html { render action: "new" }
        format.json { render json: @weight_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /weight_logs/1
  # PUT /weight_logs/1.json
  def update
    @weight_log = current_user.weight_logs.find(params[:id])

    respond_to do |format|
      if @weight_log.update_attributes(params[:weight_log])
        format.html { redirect_to @weight_log, notice: 'Weight log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @weight_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weight_logs/1
  # DELETE /weight_logs/1.json
  def destroy
    @weight_log = current_user.weight_logs.find(params[:id])
    @weight_log.destroy

    respond_to do |format|
      format.html { redirect_to weight_logs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/weight_logs_helper.rb
module WeightLogsHelper
end

app/views/weight_logs/_form.html.erb
<%= form_for(@weight_log, :url => user_weight_logs_path(current_user)) do |f| %>
  <% if @weight_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weight_log.errors.count, "error") %> prohibited this weight_log from being saved:</h2>

      <ul>
      <% @weight_log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weight_logs/edit.html.erb
<h1>Editing weight_log</h1>

<%= render 'form' %>

app/views/weight_logs/index.html.erb
<h1>Listing weight_logs</h1>

<table>
  <tr>
    <th>created</th>
    <th>weight</th>
  </tr>

<% @weight_logs.each do |weight_log| %>
  <tr>
    <td><%= weight_log.created_at.strftime("%Y-%m-%d") %></td>
    <td><%= weight_log.weight %> lbs</td>
  </tr>
<% end %>
</table>

<br />
<p>
  <h5>Starting Weight: <%= current_user.starting_weight %></h5>
</p>  
<p>
  <h5>Weight Goal: <%= current_user.weight_goal %></h5> 
</p>  
<br />

<%= link_to 'New Weight log', new_user_weight_log_path(current_user.id) %>|<%= link_to 'Edit Weight Goal', edit_user_path(current_user.id) %>

app/views/weight_logs/new.html.erb
<h1>New weight_log</h1>

<%= render 'form' %>

<%= link_to 'Back', root_url %>

app/views/weight_logs/show.html.erb
<p id="notice"><%= notice %></p>